config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  devise_for :users
  resources :dashboard,        only: %w( index )
  resources :servers,          only: %w( index )
  resources :web_applications, only: %w( index )

  namespace :admin do
    resources :users,            only:   %w( index )
    resources :servers,           except: %w( show )
    resources :web_applications, except: %w( show )
  end
  get 'admin/users/:id/admin'             => 'admin/users#admin',             as: :admin_admin_user
  get 'admin/users/:id/unadmin'           => 'admin/users#unadmin',           as: :unadmin_admin_user
  get 'admin/servers/:id/delete'          => 'admin/servers#delete',          as: :delete_admin_server
  get 'admin/web_applications/:id/delete' => 'admin/web_applications#delete', as: :delete_admin_web_application

end

app/models/server.rb
# == Schema Information
#
# Table name: servers
#
#  id                   :integer          not null, primary key
#  name                 :string(255)      default(""), not null
#  description          :text
#  ip_address           :string(255)      default(""), not null
#  static_ip_flag       :boolean          default(FALSE), not null
#  name_resolution_flag :boolean          default(FALSE), not null
#  outside_open_ports   :string(255)      default(""), not null
#  created_at           :datetime
#  updated_at           :datetime
#

class Server < ActiveRecord::Base
  validates :name, :ip_address, presence: true
  scope :id_is, -> ( id ) { where( id: id ).first }
  has_many :web_applications

  paginates_per 6

  def static_ip?
    static_ip_flag
  end

  def name_resolution?
    name_resolution_flag
  end

  def self.search( keyword )
    if keyword
      Server.where( ['name LIKE ?', "%#{keyword}%"] )
    else
      Server.all
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  uid                :string(255)      default(""), not null
#  encrypted_password :string(255)      default(""), not null
#  admin_flag         :boolean          default(FALSE), not null
#  created_at         :datetime
#  updated_at         :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :ldap_authenticatable
         # :registerable, :recoverable, :rememberable, :trackable, :validatable
  scope :id_is, -> ( id ) { where( id: id ).first }

  def admin?
    admin_flag
  end
end

app/models/web_application.rb
# == Schema Information
#
# Table name: web_applications
#
#  id          :integer          not null, primary key
#  name        :string(255)      default(""), not null
#  url         :string(255)      default(""), not null
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  server_id   :integer          default(0), not null
#

class WebApplication < ActiveRecord::Base
  validates :name, :url, presence: true
  scope :id_is, -> ( id ) { where( id: id ).first }
  belongs_to :server

  paginates_per 8

  def self.search( keyword )
    if keyword
      WebApplication.where( ['name LIKE ?', "%#{keyword}%"] )
    else
      WebApplication.all
    end
  end
end

app/controllers/admin/servers_controller.rb
class Admin::ServersController < ApplicationController
  before_action :load_server, except: %w( index new create )
  before_action :authenticate_user!
  before_action :admin_user!

  def index
    @servers = Server.all
  end

  def new
    render :show_modal_form
  end

  def create
    @server = Server.new( server_params )
    @result = @server.save
    @server = nil unless @result
    flash[:notice] = '登録しました。' if @result
  end

  def edit
    render :show_modal_form
  end

  def update
    @result = @server.update( server_params )
    @server = nil unless @result
    flash[:notice] = '更新しました。' if @result
  end

  def delete
    render :show_modal_delete
  end

  def destroy
    @result = @server.destroy
    @server = nil unless @result
    flash[:notice] = '削除しました。' if @result
    flash[:alert] = '削除できませんでした。' unless @result
    render :reload
  end

  private

  def load_server
    @server = Server.id_is( params[:id] ) if params[:id]
  end

  def server_params
    params.require( :server ).permit( :name, :description, :ip_address, :static_ip_flag, :name_resolution_flag, :outside_open_ports )
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :load_user, except: %w( index )
  before_action :authenticate_user!
  before_action :admin_user!

  def index
    @users = User.all
  end

  def admin
    @user.admin_flag = true
    @result = @user.save
    @user = nil unless @result
    flash[:notice] = '管理者権限を設定しました。' if @result
    flash[:alert] = '管理者権限を設定できませんでした。' unless @result
    render :reload
  end

  def unadmin
    @user.admin_flag = false
    @result = @user.save
    @user = nil unless @result
    flash[:notice] = '管理者権限を解除しました。' if @result
    flash[:alert] = '管理者権限を解除できませんでした。' unless @result
    render :reload
  end

  private

  def load_user
    @user = User.id_is( params[:id] ) if params[:id]
  end
end

app/controllers/admin/web_applications_controller.rb
class Admin::WebApplicationsController < ApplicationController
  before_action :load_web_application, except: %w( index new create )
  before_action :authenticate_user!
  before_action :admin_user!

  def index
    @web_applications = WebApplication.all
  end

  def new
    render :show_modal_form
  end

  def create
    @web_application = WebApplication.new( web_application_params )
    @result = @web_application.save
    @web_application = nil unless @result
    flash[:notice] = '登録しました。' if @result
  end

  def edit
    render :show_modal_form
  end

  def update
    @result = @web_application.update( web_application_params )
    @web_application = nil unless @result
    flash[:notice] = '更新しました。' if @result
  end

  def delete
    render :show_modal_delete
  end

  def destroy
    @result = @web_application.destroy
    @web_application = nil unless @result
    flash[:notice] = '削除しました。' if @result
    flash[:alert] = '削除できませんでした。' unless @result
    render :reload
  end

  private

  def load_web_application
    @web_application = WebApplication.id_is( params[:id] ) if params[:id]
  end

  def web_application_params
    params.require( :web_application ).permit( :name, :url, :server_id, :description )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from DeviseLdapAuthenticatable::LdapException do |exception|
    render :text => exception, :status => 500
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def admin_user!
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :authenticate_user!

  def index
    @servers = Server.search( params[:keyword] )
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    redirect_to dashboard_index_path if current_user
  end
end

app/controllers/web_applications_controller.rb
class WebApplicationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @web_applications = WebApplication.search( params[:keyword] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/servers/_delete.html.slim
- @title = '削除'

- modal_body = capture do
  p
    | サーバー「#{@server.name}」を削除しますか?

- modal_footer = capture do
  = link_to admin_server_path( @server.id ), class: 'btn btn-danger', remote: true, method: :delete do
    | 削除
  = content_tag :button, 'キャンセル', class: 'btn btn-default', 'data-dismiss' => 'modal'

= modal_dialog :id => 'modal-form', :header => { :show_close => true, :dismiss => 'modal', :title => @title }, body: modal_body, :footer => modal_footer

app/views/admin/servers/_form.html.slim
- unless @server
  - @server = Server.new
  - @title = '登録'
  - @button_caption = '登録'
  - @action = 'create'
- else
  - @title = '編集'
  - @button_caption = '更新'
  - @action = 'update'

= form_for @server, url: { controller: 'admin/servers', action: @action }, remote: true do |f|
  - modal_body = capture do
    .form-group
      = f.label :name, '名前', class: 'control-label'
      = f.text_field :name, autofocus: true, class: 'form-control'
    .form-group
      = f.label :description, '説明 (任意)', class: 'control-label'
      = f.text_area :description, autofocus: true, class: 'form-control', size: 'x3'
    .form-group
      = f.label :ip_address, 'IPアドレス', class: 'control-label'
      = f.text_field :ip_address, autofocus: true, class: 'form-control'
    .checkbox
      label
        | 固定IPアドレス
        = f.check_box :static_ip_flag
    .checkbox
      label
        | 名前解決可能 (DNS登録)
        = f.check_box :name_resolution_flag
    .form-group
      = f.label :outside_open_ports, '学外公開ポート (コンマ区切り)', class: 'control-label'
      .input-group
        span.input-group-addon
          = fa_icon 'tags'
        = f.text_field :outside_open_ports, autofocus: true, class: 'form-control', id: 'tokenfield'

  - modal_footer = capture do
    = f.submit @button_caption, class: 'btn btn-info'
    = content_tag :button, 'キャンセル', class: 'btn btn-default', 'data-dismiss' => 'modal'

  - modal_dialog :id => 'modal-form', :header => { :show_close => true, :dismiss => 'modal', :title => @title }, body: modal_body, :footer => modal_footer

app/views/admin/servers/_list.html.slim
- if @servers.empty?
  .alert.alert-danger 登録されているサーバーはありません。
- else
  .table-responsive
    table.table.table-bordered.table-hover
      thead
        th.center style="width: 125px;"
        th 名前
        th IPアドレス
        th 学外公開ポート
        th Webアプリ
      tbody
        - @servers.each do |server|
          tr
            td.center
              = link_to edit_admin_server_path( server.id ), class: 'btn btn-success btn-xs', remote: true do
                = fa_icon 'pencil', text: '編集'
              | &nbsp;
              = link_to delete_admin_server_path( server.id ), class: 'btn btn-danger btn-xs', remote: true do
                = fa_icon 'trash-o', text: '削除'
            td #{server.name}
            td
              | #{server.ip_address}
              - if server.static_ip? or server.name_resolution?
                br
              - if server.static_ip?
                | &nbsp;
                span.label.label-success
                  = fa_icon 'check', text: '固定IP'
              - if server.name_resolution?
                | &nbsp;
                span.label.label-success
                  = fa_icon 'check', text: '名前解決'
            td
              - server.outside_open_ports.split( ', ' ).each do |port|
                span.label.label-default #{port}
                | &nbsp;
            td
              - server.web_applications.each do |web_application|
                span.label.label-warning #{web_application.name}
                | &nbsp;

app/views/admin/servers/index.html.slim
- @title = 'サーバー管理'

h3.bold
  = fa_stacked_icon 'hdd-o inverse', base: 'square', text: @title

= link_to new_admin_server_path, class: 'btn btn-info', remote: true do
  = fa_icon 'plus', text: '登録'

p

= render partial: 'admin/servers/list'

app/views/admin/users/_list.html.slim
- if @users.empty?
  strong 登録されているユーザーはいません。
- else
  .table-responsive
    table.table.table-bordered.table-hover.table-striped
      thead
        th アカウント名
        th.center style="width: 75px; "管理者
      tbody
        - @users.each do |user|
          tr
            td #{user.uid}
            td.center
              - if user.id == current_user.id
                button.btn.btn-default.btn-xs disabled="true"
                  = fa_icon 'user', text: '自分'
              - elsif user.admin?
                = link_to unadmin_admin_user_path( user.id ), class: 'btn btn-danger btn-xs', remote: true do
                  = fa_icon 'minus', text: '剥奪'
              - else
                = link_to admin_admin_user_path( user.id ), class: 'btn btn-success btn-xs', remote: true do
                  = fa_icon 'plus', text: '付与'

app/views/admin/users/index.html.slim
- @title = 'ユーザー管理'

h3.bold
  = fa_stacked_icon 'user inverse', base: 'square', text: @title

= render partial: 'admin/users/list'

app/views/admin/web_applications/_list.html.slim
- if @web_applications.empty?
  .alert.alert-danger 登録されているWebアプリはありません。
- else
  .table-responsive
    table.table.table-bordered.table-hover.table-striped
      thead
        th.center style="width: 125px;"
        th 名前
        th URL
        th サーバー
      tbody
        - @web_applications.each do |web_application|
          tr
            td.center
              = link_to edit_admin_web_application_path( web_application.id ), class: 'btn btn-success btn-xs', remote: true do
                = fa_icon 'pencil', text: '編集'
              | &nbsp;
              = link_to delete_admin_web_application_path( web_application.id ), class: 'btn btn-danger btn-xs', remote: true do
                = fa_icon 'trash-o', text: '削除'
            td #{web_application.name}
            td
              = link_to web_application.url, class: 'btn btn-default btn-xs', target: '_blank' do
                = fa_icon 'external-link', text: web_application.url
            td #{web_application.server.name}

app/views/admin/web_applications/index.html.slim
- @title = 'Webアプリ管理'

h3.bold
  = fa_stacked_icon 'globe inverse', base: 'square', text: @title

= link_to new_admin_web_application_path, class: 'btn btn-info', remote: true do
  = fa_icon 'plus', text: '登録'

p

= render partial: 'admin/web_applications/list'

app/views/dashboard/index.html.slim
- @title = 'ダッシュボード'

h3.bold
  = fa_stacked_icon 'dashboard inverse', base: 'square', text: @title

app/views/layouts/application.html.slim
doctype html
html
  head
    title #{@title} | SLP Portal
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'application', 'data-turbolinks-track' => true, media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    link href="http://fonts.googleapis.com/css?family=Exo:800italic" rel="stylesheet" type="text/css"

  body
    .modal-form

    nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to root_path, class: "navbar-brand" do
            | SLP Portal

        .collapse.navbar-collapse id="bs-example-navbar-collapse-1"
          - if current_user
            ul.nav.navbar-nav
              li
                = link_to dashboard_index_path do
                  = fa_icon 'dashboard', text: 'ダッシュボード'
              li
                = link_to servers_path do
                  = fa_icon 'hdd-o', text: 'サーバー'
              li
                = link_to web_applications_path do
                  = fa_icon 'globe', text: 'Webアプリ'
              - if current_user.admin?
                li.dropdown
                  a.dropdown-toggle href="#" data-toggle="dropdown"
                    = fa_icon 'cog', text: '管理'
                    | &nbsp;
                    b.caret
                  ul.dropdown-menu
                    li
                      = link_to admin_users_path do
                        = fa_icon 'user', text: 'ユーザー'
                    li
                      = link_to admin_servers_path do
                        = fa_icon 'hdd-o', text: 'サーバー'
                    li
                      = link_to admin_web_applications_path do
                        = fa_icon 'globe', text: 'Webアプリ'
            ul.nav.navbar-nav.navbar-right
              li.dropdown
                a.dropdown-toggle href="#" data-toggle="dropdown"
                  = fa_icon 'user', text: current_user.uid
                  | &nbsp;
                  b.caret
                ul.dropdown-menu
                  li
                    = link_to destroy_user_session_path, method: :delete do
                      = fa_icon 'sign-out', text: 'ログアウト'

    .container
      - if notice
        .alert.alert-info.alert-dismissable
          button.close type="button" data-dismiss="alert" aria-hidden="true" &times;
          = notice
      - if alert
        .alert.alert-danger.alert-dismissable
          button.close type="button" data-dismiss="alert" aria-hidden="true" &times;
          = alert
      = yield
      footer.right
        small &copy; Student Laboratory of Programming
        p

app/views/servers/_list.html.slim
- if @servers.empty?
  .alert.alert-danger 登録されているサーバーはありません。
- else
  .table-responsive
    table.table.table-bordered.table-hover.table-striped
      thead
        th 名前
        th IPアドレス
        th 学外公開ポート
        th Webアプリ
        th 説明
      tbody
        - @servers.each do |server|
          tr
            td #{server.name}
            td
              | #{server.ip_address}
              - if server.static_ip? or server.name_resolution?
                br
              - if server.static_ip?
                | &nbsp;
                span.label.label-success
                  = fa_icon 'check', text: '固定IP'
              - if server.name_resolution?
                | &nbsp;
                span.label.label-success
                  = fa_icon 'check', text: '名前解決'
            td
              - server.outside_open_ports.split( ', ' ).each do |port|
                span.label.label-default #{port}
                | &nbsp;
            td
              - server.web_applications.each do |web_application|
                span.label.label-warning #{web_application.name}
                | &nbsp;
            td #{simple_format server.description}

app/views/servers/index.html.slim
- @title = 'サーバー'

.row
  .col-md-8
    h3.bold
      = fa_stacked_icon 'hdd-o inverse', base: 'square', text: @title
  .col-md-4
    p
    = form_tag servers_path, method: :get, class: 'form' do
      .input-group
        span.input-group-addon
          = fa_icon 'search'
        = text_field_tag :keyword, params[:keyword], class: 'form-control'
    p

= render partial: 'servers/list'

app/views/top/index.html.slim
= render file: '/devise/sessions/new'

app/views/web_applications/_list.html.slim
- if @web_applications.empty?
  .alert.alert-danger 登録されているWebアプリはありません。
- else
  .table-responsive
    table.table.table-bordered.table-hover.table-striped
      thead
        th 名前
        th URL
        th サーバー
        th 説明
      tbody
        - @web_applications.each do |web_application|
          tr
            td #{web_application.name}
            td
              = link_to web_application.url, class: 'btn btn-default btn-xs', target: '_blank' do
                = fa_icon 'external-link', text: web_application.url
            td #{web_application.server.name}
            td #{simple_format web_application.description}

app/views/web_applications/index.html.slim
- @title = 'Webアプリ'

.row
  .col-md-8
    h3.bold
      = fa_stacked_icon 'globe inverse', base: 'square', text: @title
  .col-md-4
    p
    = form_tag web_applications_path, method: :get, class: 'form' do
      .input-group
        span.input-group-addon
          = fa_icon 'search'
        = text_field_tag :keyword, params[:keyword], class: 'form-control'
    p

= render partial: 'web_applications/list'